function f = minimizedFun(in1,in2,in3,in4,in5,in6)
%MINIMIZEDFUN
%    F = MINIMIZEDFUN(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-Oct-2015 00:42:32

x1 = in1(1,:);
x2 = in1(2,:);
A1 = in2(1,:);
A2 = in2(2,:);
A3 = in2(3,:);
B1 = in3(1,:);
B2 = in3(2,:);
B3 = in3(3,:);
C1 = in4(1,:);
C2 = in4(2,:);
C3 = in4(3,:);
D1 = in5(1,:);
D2 = in5(2,:);
D3 = in5(3,:);
Y1 = in6(1,:);
Y2 = in6(2,:);
Y3 = in6(3,:);
t2 = x2-1.0;
t3 = x1-1.0;
t4 = Y1-A1.*t2.*t3+B1.*t2.*x1+D1.*t3.*x2-C1.*x1.*x2;
t5 = Y2-A2.*t2.*t3+B2.*t2.*x1+D2.*t3.*x2-C2.*x1.*x2;
t6 = Y3-A3.*t2.*t3+B3.*t2.*x1+D3.*t3.*x2-C3.*x1.*x2;
f = t4.^2+t5.^2+t6.^2;
