Description of bernstein
Home > GSpline > bernstein.m
bernstein
PURPOSE
BERNSTEIN calculates i-th bernstein polynomial of degree n at t.
SYNOPSIS
function [ B ] = bernstein(i,n,t)
DESCRIPTION
BERNSTEIN calculates i-th bernstein polynomial of degree n at t.
CROSS-REFERENCE INFORMATION
This function calls:
bincoeff BINCOEFF calculates binomial coefficient: n! / k! / (n-k)!
This function is called by:
bezier BEZIER Returns x,y,z values of a 3D bezier-curve with the given control points P and
bezierRational BEZIERRATIONAL Returns x,y values of a bezier-curve with the given control points P , weights w and
getBezierPointCoefs Spits out a 3x3 matrix of the coefficients on the neighbouring (and
getBicubicBezierPointCoefs Spits out an mx4 matrix of the coefficients on the neighbouring (and
SOURCE CODE
function [ B ] = bernstein(i,n,t)
%BERNSTEIN calculates i-th bernstein polynomial of degree n at t.
B=bincoeff(n,i).*t.^i .* (1-t).^(n-i);
end