Description of getNumOfEdgesMeetingMatlab
Home > GSpline > getNumOfEdgesMeetingMatlab.m
getNumOfEdgesMeetingMatlab
PURPOSE
GETNUMOFEDGESMEETING Summary of this function goes here
SYNOPSIS
function [ numOfEdgesMeeting ] = getNumOfEdgesMeetingMatlab(neighbour_matrix, orig_vertex_id_matlab)
DESCRIPTION
GETNUMOFEDGESMEETING Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkB1B2OrientationReversal check if the B1 in the quad to the right lies along the same edge as the
createGlobalControlMeshCoefs takes, for N datapoints, an array parameterCoordinates[Nx3](for every
getExtraOrdCornerIndexMask
plotAsBsCs
rotateB2Matlab
rotateB2fromB1
sortAB1B2VIndices
sortB1B2Indices
SOURCE CODE
function [ numOfEdgesMeeting ] = getNumOfEdgesMeetingMatlab(neighbour_matrix, orig_vertex_id_matlab)
%GETNUMOFEDGESMEETING Summary of this function goes here
%   Detailed explanation goes here
numOfEdgesMeeting = sum(neighbour_matrix(orig_vertex_id_matlab,:,1) ~= 0);
end