Description of petersPlot
Home > GSpline > petersPlot.m
petersPlot
PURPOSE
% Peter's scheme plot
SYNOPSIS
function handle = petersPlot(points,stepsize)
DESCRIPTION
% Peter's scheme plot
 Plot of a mesh using peter's scheme
CROSS-REFERENCE INFORMATION
This function calls:
bezier BEZIER Returns x,y,z values of a 3D bezier-curve with the given control points P and
getBiquadraticPatch given a 3x3 3-dim array of points, where the first dimension is (x,y,z)
plotPoints
This function is called by:
torusPointsScript
SOURCE CODE
function handle = petersPlot(points,stepsize)
%% Peter's scheme plot
% Plot of a mesh using peter's scheme
m = size(points,2);
n = size(points,3);
handle = figure('Name', 'Peters plot');
plotPoints(points);
hold on
for j = 2:(n-1)
    for i = 2:(m-1)
        neighbours = points(:,(i-1):(i+1),(j-1):(j+1));
        bezierPoints = getBiquadraticPatch(neighbours);
        plotPoints(bezierPoints);
        [x,y,z] = bezier(bezierPoints,stepsize);
        surf(x,y,z);
    end
end