Description of plotPatchesOnQuad
Home > GSpline > plotPatchesOnQuad.m
plotPatchesOnQuad
PURPOSE
SYNOPSIS
function plotHandle = plotPatchesOnQuad(quad_list,AVertexList,B1VertexList,B2VertexList,CVertexList,quad_control_point_indices,control_points,quad_index,patch_list,plotHandle)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
bezier BEZIER Returns x,y,z values of a 3D bezier-curve with the given control points P and
get3x3ControlPointIndexMask
getBicubicPatchIndex nomenclature following that of paper of Eck, Hoppe (Automatic
getBiquadraticPatch given a 3x3 3-dim array of points, where the first dimension is (x,y,z)
getExtraOrdCornerIndexMask
This function is called by:
plotQuadOrQuadsWithHairs % script to create model torus quads
SOURCE CODE
function plotHandle = plotPatchesOnQuad(quad_list,AVertexList,B1VertexList,B2VertexList,CVertexList,quad_control_point_indices,control_points,quad_index,patch_list,plotHandle)
whichCornerList = [1,4;2,3];
one4toone2 = @(i) (i-1)/3 + 1;
whichCornerFun = @(i,j) whichCornerList(one4toone2(i),one4toone2(j));
controlVertices = zeros(3,3,3);
mod_index = @(index,modul) mod(index-1,modul) + 1;
indexToI = @(index) mod_index(index,4);
indexToJ = @(index) (index - indexToI(index))/4 + 1;
figure(plotHandle);
% = figure('Name', 'Bezier surface plot');
hold on;
q = quad_index;
for index = patch_list
    j = indexToJ(index);
    i = indexToI(index);
    if ([i,j]==1 | [i,j] == 4)
        whichCorner = whichCornerFun(i,j);
        indexMask = getExtraOrdCornerIndexMask(quad_list,AVertexList,B1VertexList,B2VertexList,CVertexList,quad_control_point_indices,q,whichCorner);
        numberOfEdges = size(indexMask,2);
        As =  control_points(indexMask(1,:),:)';
        B1s =  control_points(indexMask(2,:),:)';
        B2s =  control_points(indexMask(3,:),:)';
        Cs =  control_points(indexMask(4,:),:)';
        Bs = cat(2,reshape(B1s,3,1,numberOfEdges),reshape(B2s,3,1,numberOfEdges));
        patch = getBicubicPatchIndex(1,As,Bs,Cs);
        %     patch(:,3,3) = rot(pi)*patch(:,3,3);
%         plotPoints(patch);
        [xx,yy,zz]=bezier(patch,0.1);
        surf(xx,yy,zz)
    else
        neighbourMask = get3x3ControlPointIndexMask(quad_list,quad_control_point_indices,q,[i,j]);
        for bezierJ = 1:3
            for bezierI = 1:3
                controlVertices(:,bezierI,bezierJ) = control_points(neighbourMask(bezierI,bezierJ),:);
            end
        end
        APatch = getBiquadraticPatch(controlVertices);
        %     patch(:,3,3) = rot(pi)*patch(:,3,3);
%         plotPoints(APatch);
        [xx,yy,zz]=bezier(APatch,0.1);
        surf(xx,yy,zz)
    end
end
end