Description of plotPoints
Home > GSpline > plotPoints.m
plotPoints
PURPOSE
SYNOPSIS
function tempMatrix = plotPoints(points)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ExtraOrdExtend % this is put on hold for feasible closed geometry with extraordinary faces
ExtraOrdTorusTest
extraOrdCorner
petersPlot % Peter's scheme plot
torusPointsScript
SOURCE CODE
function tempMatrix = plotPoints(points)
m = size(points,2);
n = size(points,3);
% create temporary matrix
tempMatrix = zeros(3,n*m);
tempMatrixIndex = @(i,j, width) (i-1)*width + j;
for j = 1:n
    for i  = 1:m
        tempMatrix(:,tempMatrixIndex(i,j,n)) = points(:,i,j);
    end
end
scatter3(tempMatrix(1,:),tempMatrix(2,:),tempMatrix(3,:));
end