Description of sortAB1B2VIndices
Home > GSpline > sortAB1B2VIndices.m
sortAB1B2VIndices
PURPOSE
SYNOPSIS
function [newA,newB1,newB2,newC] = sortAB1B2VIndices(oldA,oldB1,oldB2,oldC)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
getNumOfEdgesMeetingMatlab GETNUMOFEDGESMEETING Summary of this function goes here
This function is called by:
loadingScript % script for loading data and preformatting the indices for matlab
loadingTorus % script for loading data and preformatting the indices for matlab
SOURCE CODE
function [newA,newB1,newB2,newC] = sortAB1B2VIndices(oldA,oldB1,oldB2,oldC)
mod_index = @(i,modul) mod(i-1,modul) + 1;
shifted_indices = @(ind,modul) mod_index((0:(modul-1)) + ind,modul);
newB1 = zeros(size(oldB1));
newB2 = zeros(size(oldB2));
newA = zeros(size(oldA));
newC = zeros(size(oldC));
for i = 1:size(oldB2,1)
    m = getNumOfEdgesMeetingMatlab(oldB2,i);
    indicesLocB1 = zeros(1,m);
    indicesLocB2 = zeros(1,m);
    indicesLocA = zeros(1,m);
    indicesLocC = zeros(1,m);
    [~,B1Indices,B2Indices] = intersect(reshape(oldB1(i,1:m,3:4),m,2),reshape(oldB2(i,1:m,3:4),m,2),'rows');
    nextIndex = 1;
    for local_quad_index = 1:m
        current_quad = B2Indices(nextIndex);
        neighbour = B1Indices(nextIndex);
        neighbourQuad = oldB1(i,neighbour,2);
        neighbourAIndex = find(oldA(i,1:m,2) == neighbourQuad);
        neighbourB2Index = find(oldB2(i,1:m,2) == neighbourQuad);
        neighbourCIndex = find(oldC(i,1:m,2) == neighbourQuad);
        nextIndex = find(B2Indices == neighbourB2Index);
        indicesLocA(mod_index(local_quad_index+1,m)) = neighbourAIndex;
        indicesLocB1(mod_index(local_quad_index+1,m)) = neighbour;
        indicesLocC(mod_index(local_quad_index+1,m)) = neighbourCIndex;
        indicesLocB2(local_quad_index) = current_quad;
    end
    newA(i,1:m,:) = oldA(i,indicesLocA,:);
    newB1(i,1:m,:) = oldB1(i,indicesLocB1,:);
    newB2(i,1:m,:) = oldB2(i,indicesLocB2,:);
    newC(i,1:m,:) = oldC(i,indicesLocC,:);
end